import type { MaintainerRepository } from "./types";

export const demoRepository: MaintainerRepository = {
  identity: {
    owner: "openmaintainer",
    name: "demo-repo",
    fullName: "openmaintainer/demo-repo",
    url: "https://github.com/openmaintainer/demo-repo",
  },
  description:
    "A demo repository used to show how OpenMaintainer helps maintainers triage issues and review pull requests.",
  stars: 1284,
  forks: 96,
  watchers: 42,
  openIssues: 37,
  defaultBranch: "main",
  license: "MIT",
  updatedAt: "2026-05-30T10:15:00Z",
  issues: [
    {
      id: 1,
      number: 284,
      title: "Windows install fails when pnpm is not already available",
      body: "The setup script exits with command not found on Windows 11. I tried npm install and then pnpm dev, but pnpm is missing.",
      author: "first-time-contributor",
      labels: [],
      comments: 2,
      createdAt: "2026-05-29T12:30:00Z",
      updatedAt: "2026-05-30T08:01:00Z",
      url: "https://github.com/openmaintainer/demo-repo/issues/284",
    },
    {
      id: 2,
      number: 285,
      title: "Add Chinese README quickstart",
      body: "A short zh-CN quickstart would help independent developers understand the workflow faster.",
      author: "cn-maintainer",
      labels: ["good first issue"],
      comments: 4,
      createdAt: "2026-05-29T14:20:00Z",
      updatedAt: "2026-05-30T09:20:00Z",
      url: "https://github.com/openmaintainer/demo-repo/issues/285",
    },
    {
      id: 3,
      number: 286,
      title: "Question: can the triage model run without an API key?",
      body: "I want to use this in a public workshop without requiring every attendee to create credentials.",
      author: "workshop-host",
      labels: ["question"],
      comments: 1,
      createdAt: "2026-05-30T03:10:00Z",
      updatedAt: "2026-05-30T06:45:00Z",
      url: "https://github.com/openmaintainer/demo-repo/issues/286",
    },
    {
      id: 6,
      number: 287,
      title: "Install script fails on Windows when pnpm is missing",
      body: "Fresh Windows machine, Node 22 installed. Running npm run setup fails because pnpm is not recognized.",
      author: "windows-user",
      labels: [],
      comments: 1,
      createdAt: "2026-05-30T07:10:00Z",
      updatedAt: "2026-05-30T09:05:00Z",
      url: "https://github.com/openmaintainer/demo-repo/issues/287",
    },
  ],
  pullRequests: [
    {
      id: 4,
      number: 92,
      title: "Refactor GitHub adapter error handling",
      body: "This consolidates fetch errors and adds user-facing messages for rate limits and missing permissions.",
      author: "adapter-owner",
      additions: 214,
      deletions: 87,
      changedFiles: 6,
      labels: ["refactor"],
      createdAt: "2026-05-29T11:00:00Z",
      updatedAt: "2026-05-30T07:30:00Z",
      url: "https://github.com/openmaintainer/demo-repo/pull/92",
    },
    {
      id: 5,
      number: 93,
      title: "Add release notes generator",
      body: "Adds grouped release notes from merged pull requests and labeled issues.",
      author: "release-captain",
      additions: 128,
      deletions: 12,
      changedFiles: 3,
      labels: ["feature"],
      createdAt: "2026-05-30T04:00:00Z",
      updatedAt: "2026-05-30T09:40:00Z",
      url: "https://github.com/openmaintainer/demo-repo/pull/93",
    },
  ],
};
