/**
 * PR Template Generator - Generate standard PR response templates
 */

export interface PRTemplateOptions {
  prTitle: string;
  prNumber: number;
  author: string;
  reviewStatus: "approved" | "changes_requested" | "pending" | "commented";
  reviewSummary?: string;
  language?: "en" | "zh";
}

const templates = {
  en: {
    approved: (opts: PRTemplateOptions) => `## 🎉 PR Approved!

**#{number}** - *{title}*
Submitted by @{author}

Great work! Your contribution has been approved and will be merged soon.

${opts.reviewSummary ? `### Review Summary\n${opts.reviewSummary}\n` : ''}---
*Generated by [OpenMaintainer](https://openmaintainer.vercel.app)*`,

    changesRequested: (opts: PRTemplateOptions) => `## 📝 Changes Requested

**#{number}** - *{title}*
Submitted by @{author}

Thank you for your contribution! Before we can merge this PR, some changes are needed.

${opts.reviewSummary ? `### Review Feedback\n${opts.reviewSummary}\n` : ''}Please address the above feedback and resubmit. Feel free to reach out if you have any questions!

---
*Generated by [OpenMaintainer](https://openmaintainer.vercel.app)*`,

    pending: (opts: PRTemplateOptions) => `## ⏳ PR Under Review

**#{number}** - *{title}*
Submitted by @{author}

Thank you for your contribution! Your PR is currently under review.

We'll get back to you as soon as possible. In the meantime, please make sure:
- Your branch is up to date with the target branch
- All tests pass
- You've addressed any existing comments

---
*Generated by [OpenMaintainer](https://openmaintainer.vercel.app)*`,

    commented: (opts: PRTemplateOptions) => `## 💬 PR Commented

**#{number}** - *{title}*
Submitted by @{author}

Thank you for your contribution! I've left some comments on your PR.

${opts.reviewSummary ? `### My Comments\n${opts.reviewSummary}\n` : ''}Please review the comments and let me know if you have any questions!

---
*Generated by [OpenMaintainer](https://openmaintainer.vercel.app)*`,
  },
  zh: {
    approved: (opts: PRTemplateOptions) => `## 🎉 PR 已批准！

**#{number}** - *{title}*
提交者：@{author}

太棒了！您的贡献已被批准，将会尽快合并。

${opts.reviewSummary ? `### 评审总结\n${opts.reviewSummary}\n` : ''}---
*由 [OpenMaintainer](https://openmaintainer.vercel.app) 生成*`,

    changesRequested: (opts: PRTemplateOptions) => `## 📝 需要修改

**#{number}** - *{title}*
提交者：@{author}

感谢您的贡献！在合并此 PR 之前，需要进行一些修改。

${opts.reviewSummary ? `### 评审反馈\n${opts.reviewSummary}\n` : ''}请解决上述反馈并重新提交。如有任何问题，请随时联系！

---
*由 [OpenMaintainer](https://openmaintainer.vercel.app) 生成*`,

    pending: (opts: PRTemplateOptions) => `## ⏳ PR 审核中

**#{number}** - *{title}*
提交者：@{author}

感谢您的贡献！您的 PR 正在审核中。

我们会尽快回复您。同时，请确保：
- 您的分支与目标分支保持同步
- 所有测试通过
- 您已回复所有现有评论

---
*由 [OpenMaintainer](https://openmaintainer.vercel.app) 生成*`,

    commented: (opts: PRTemplateOptions) => `## 💬 PR 已评论

**#{number}** - *{title}*
提交者：@{author}

感谢您的贡献！我在您的 PR 上留下了一些评论。

${opts.reviewSummary ? `### 我的评论\n${opts.reviewSummary}\n` : ''}请查看评论，如有任何问题请告诉我！

---
*由 [OpenMaintainer](https://openmaintainer.vercel.app) 生成*`,
  },
};

/**
 * Generate a PR response template
 */
export function generatePRTemplate(opts: PRTemplateOptions): string {
  const lang = opts.language || "en";
  const templateSet = templates[lang];
  const templateFn = templateSet[opts.reviewStatus];
  
  return templateFn(opts)
    .replace('{number}', opts.prNumber.toString())
    .replace('{title}', opts.prTitle)
    .replace('{author}', opts.author);
}

/**
 * Get available template types
 */
export function getTemplateTypes() {
  return [
    { value: "approved", label: "Approved", labelZh: "已批准" },
    { value: "changes_requested", label: "Changes Requested", labelZh: "需要修改" },
    { value: "pending", label: "Under Review", labelZh: "审核中" },
    { value: "commented", label: "Commented", labelZh: "已评论" },
  ] as const;
}
